const GOLDEN_RATIO = 1.61803398875; // The golden ratio constant

const BASE_FONT_SIZE = 18; // The base font size in pixels

export const ONE = {
  DESKTOP: BASE_FONT_SIZE * GOLDEN_RATIO * GOLDEN_RATIO * 5.5,
  TABLET: BASE_FONT_SIZE * GOLDEN_RATIO * GOLDEN_RATIO * 4,
  MOBILE: BASE_FONT_SIZE * GOLDEN_RATIO,
};

export const TWO = {
  DESKTOP: BASE_FONT_SIZE * GOLDEN_RATIO * GOLDEN_RATIO * 3,
  TABLET: BASE_FONT_SIZE * GOLDEN_RATIO * 2.5,
  MOBILE: BASE_FONT_SIZE * GOLDEN_RATIO * 1,
};

export const THREE = {
  DESKTOP: BASE_FONT_SIZE * GOLDEN_RATIO * 2.5,
  TABLET: BASE_FONT_SIZE * GOLDEN_RATIO * 2,
  MOBILE: BASE_FONT_SIZE * GOLDEN_RATIO * 1.5,
};

export const FOUR = {
  DESKTOP: BASE_FONT_SIZE * GOLDEN_RATIO * 2,
  TABLET: BASE_FONT_SIZE * GOLDEN_RATIO * 1.5,
  MOBILE: BASE_FONT_SIZE * GOLDEN_RATIO * 1,
};

export const FIVE = {
  DESKTOP: BASE_FONT_SIZE * GOLDEN_RATIO * 1.5,
  TABLET: BASE_FONT_SIZE * GOLDEN_RATIO * 1,
  MOBILE: BASE_FONT_SIZE * GOLDEN_RATIO * 1,
};

export const COPY = {
  DESKTOP: BASE_FONT_SIZE,
  TABLET: BASE_FONT_SIZE,
  MOBILE: BASE_FONT_SIZE,
};
